### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by karkraeg** [jdmonaco/pdf-title-rename#2]
Hi! Thanks for fix #1, works fine now! Alas, PDFs with Umlauts in them like `ö` or `ä` Output an error now (beforehand, the umlaut character was just bypassed):

    Traceback (most recent call last):
      File "/usr/bin/pdf-title-rename.py", line 236, in <module>
        sys.exit(RenamePDFsByTitle(args).main())
      File "/usr/bin/pdf-title-rename.py", line 63, in main
        title, author = self._get_info(f)
      File "/usr/bin/pdf-title-rename.py", line 128, in _get_info
        title = ti.decode()
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 5: ordinal not in range(128)

I’ve changed the Metadata for the 314.pdf accordingly if you like to look into that (https://transfer.sh/RfnsE/314.pdf). Adding `# -*- coding: utf-8 -*-` at the beginning does not help…

**Comment by jdmonaco** [comment]
The Umlaut issue is due to the encoding of your metadata. In your updated file, the parsed title looks like this

    b'Bibli\xf6metrics \xe4nd Citation Analysis'

This string is not encoded with UTF-8 (default for python and this script) or ascii (the fallback). The `0xf6` byte for `ö` indicates ISO-8859-1 encoding. This script assumes the inputs are using the most widely used standard for encoding (UTF-8). There is no easy way to figure out the encoding unless the user tells the script.

For now, I have added better handling for these errors, so it will at least print out the bytes that cannot be decoded:

```
Processing "314.pdf":
 -- Could not decode title bytes: b'Bibli\xf6metrics \xe4nd Citation Analysis'
 -- Could not find metadata in the file
Processed 1 files [dry run]:
 - Renamed: 0
 - Missing metadata: 1
 - Errors: 0
```

A better fix in the future might be to have command-line options for different encodings like ISO-8859-1, but I'm not sure of the best way to do that now.

**Comment by jdmonaco** [comment]
There may be a way around this, since you said it was bypassing those characters before. I'll put some thought into it and update sometime later if I find a better solution. Sorry for all the trouble!
