### ISSUE TITLE
Some files won't be processed

### ISSUE THREAD

**Issue by kastnerp** [jdmonaco/pdf-title-rename#3]
For some PDFs I receive the following error:

> Traceback (most recent call last):
  File "pdf-title-rename.py", line 242, in <module>
    sys.exit(RenamePDFsByTitle(args).main())
  File "pdf-title-rename.py", line 63, in main
    title, author = self._get_info(f)
  File "pdf-title-rename.py", line 123, in _get_info
    info = self._get_metadata(pdf)
  File "pdf-title-rename.py", line 193, in _get_metadata
    return doc.info[0]
IndexError: list index out of range

I can provide the PDFs if you are willing to look into it.

Best,

Patrick

**Comment by jdmonaco** [comment]
It looks like the parser isn't finding metadata but also not throwing the expected exception. I can add a check for this condition, but it's possible the pdf is getting parsed differently by pdfminer. If you could attach an example file, I can verify what's happening and find a fix. Thanks!

**Comment by kastnerp** [comment]
Thank you for taking a look!
This was one of the files: http://global.ctbuh.org/resources/papers/download/3346-bioclimatic-comfort-design-for-high-rises.pdf

**Comment by jdmonaco** [comment]
As I suspected, the file was parsed without throwing an exception but had an empty "info" list from the parser. So I added a check for the empty list to prevent the crash, but this is one of the increasing number of pdfs out there without standard metadata! Sorry for the inconvenience, but I hope this script has otherwise been useful to you.

**Comment by kastnerp** [comment]
The tool is extremely helpful, thank you for fixing it!
