### ISSUE TITLE
Suggestion for alternative output style

### ISSUE THREAD

**Issue by MooersLab** [jdmonaco/pdf-title-rename#4]
Thank you for developing and sharing this tool.

I have a suggestion to make it more useful to academics.
I do not need the last authors first name. 
Instead, I need the year of publication for citations in academic papers.

I now manually renamed my pdfs in the style of 

firstAurhtorsLastNameYeartitleInCamelCase.pdf

with the the whitespaes, dashes, and hyphens removed. 
I only really need the first 5 to 7 words of the title.

I find that the file stem in this format makes a useful 
bibtex citekey. This greatly eases finding the right cite key from the 
pulldown of citekeys that pops up in Overleaf or vim or Sublime Text 3 when 
you start to type \cite{.

The matching of the bibtex cite key and the pdf file stem makes it easier to find the pdf on my harddrive.

**Comment by jdmonaco** [comment]
Thanks for your suggestions. There are some useful improvements that could be made in this direction, but the specific case of creating bibtex cite-keys is not something that would work generally for everyone, since everyone (including me) has very different preferences.

For limiting title length, total filename size is already limited to 255 characters, which is compatible with most operating systems. However, you could fork the code and edit [Line 153](https://github.com/jdmonaco/pdf-title-rename/blob/master/pdf-title-rename.py#L153) to just retain the first N words: 

```python
            title = ' '.join(title.split()[:N]).strip()
```

Also, there is variability in how author names are stored in pdfs by publishers, so the script does not always work perfectly. For author information stored in the XMP metadata, the script extracts just the surnames of the first and last authors, otherwise the entire 'Author' field is used. This is because that information field is not standardized, making it difficult to figure out how to parse it correctly for a given pdf. 

The hyphen between author and title is added on [Line 111](https://github.com/jdmonaco/pdf-title-rename/blob/1ac0cb5ede3ccda934394120ab660842dd614fc6/pdf-title-rename.py#L111), so you could edit that to your preferred format. Further, if you edit the return value of the `_sanitize()` function on [Line 117](https://github.com/jdmonaco/pdf-title-rename/blob/1ac0cb5ede3ccda934394120ab660842dd614fc6/pdf-title-rename.py#L117), you could convert the title and authors to CamelCase:

```python
        title_with_spaces = "".join(c for c in s if c.isalnum() or c in keep)
        return "".join(map(str.title, title_with_spaces.split())).strip()
```

To only show the first author's last name, at least in the XMP metadata which is more structured, you could change [Lines 221-224](https://github.com/jdmonaco/pdf-title-rename/blob/1ac0cb5ede3ccda934394120ab660842dd614fc6/pdf-title-rename.py#L221-L224) to just these two lines:

```python
            if len(a) > 0:
                a = self._au_last_name(a[0])
```

Unfortunately I couldn't find a consistent way to extract publication year.

---

Anyway, I tell you all this because the intention of this script is not to be a general purpose bibliographic tool, but to be a first-pass attempt to bring order to a bunch of downloaded papers with filenames like ``1-s2.0-S0960982216300859-main.pdf``. That's why I would like to keep it as simple as possible, even though it fails in some cases and isn't very customizable. I encourage you to fork this repo and make the edits above to achieve what you want. (Note that I haven't tested the above changes, but they should be about right for what you need.)

The script should make it easier to add a batch of files into an actual reference manager like BibDesk or Zotero. Especially if you use bibtex, I would recommend the [BibDesk](https://bibdesk.sourceforge.io) manager which has very customizable cite-keys, and you can set it to automatically rename pdfs with filenames based on those cite-keys.
